services:

  ocr:
    container_name: ${COMPOSE_PROJECT_NAME:-archeotag}-ocr
    build:
      context: "."
      dockerfile: docker/ocr/Dockerfile
    environment:
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/5/tessdata
    profiles: [app]
